---
# Source: edgesql/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: edgesql-secret
  namespace: phoenix-prod
  labels:
    namespace: phoenix-prod
stringData:
  SA_PASSWORD: vmuTaXjX5QMQTT==
  edgesql-password: vmuTaXjX5QMQTT==
---
# Source: edgesql/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgesql-pvc
  namespace: phoenix-prod
  labels:
    namespace: phoenix-prod
spec:
  resources:
    requests:
      storage: 10Gi
---
# Source: edgesql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: edgesql-service
  namespace: phoenix-prod
  labels:
    namespace: phoenix-prod
---
# Source: edgesql/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgesql
  namespace: phoenix-prod
  labels:
    namespace: phoenix-prod
spec:
  replicas: 2
  template:
    spec:
      containers:
        - resources:
            requests:
              memory: 64Mi
              cpu: 125m
            limits:
              memory: 10Gi
              cpu: 1000m
