bases:
  #   - patches/namespace.yaml
  - ../../bases

namespace: phoenix-stage

# Affect images across all deployments, does not add ase-ecr-credentials!
# images:
#   - name: docker.io/bitnami/rabbitmq
#     newName: ecr.ase-usgva-p21.missionready.local:31001/bitnami/rabbitmq
#     newTag: 3.9.13-debian-10-r38

patches:
  - path: patches/rabbitmq_stateful_set.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: rabbitmq
  - path: patches/any_pvc.yaml
    target:
      kind: PersistentVolumeClaim
# secretGenerator:
#   - name: edgesql-secret
#     envs:
#       - patches/edgesql.env
# - target:
#     kind: Secret
#     name: edgesql-secret
#   path: patches/edgesql.yaml
