apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.data }}
spec:
  storageClassName: {{ .Values.pvc.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}
