apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus
    chart: prometheus-15.8.0
    component: server
    heritage: Helm
    release: phoenix-prometheus
  name: phoenix-prometheus-server
  namespace: phoenix-stage
spec:
  storageClassName: ase-node-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
