---
# Source: edgesql/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: edgesql-secret
  namespace: "phoenix-stage"
  labels:
    namespace: phoenix-stage
    helm.sh/chart: edgesql-0.1.0
    app.kubernetes.io/name: edgesql
    app.kubernetes.io/instance: stage
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  SA_PASSWORD: vmuTaXjX5QMQTT==
  edgesql-password: vmuTaXjX5QMQTT==
  edgesql-username: sa
  edgesql-hostname: edgesql-service
---
# Source: edgesql/templates/pvc-edge-sql.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgesql-pvc
  namespace: "phoenix-stage"
  labels:
    namespace: phoenix-stage
    helm.sh/chart: edgesql-0.1.0
    app.kubernetes.io/name: edgesql
    app.kubernetes.io/instance: stage
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  storageClassName: ase-node-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# Source: edgesql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: edgesql-service
  namespace: "phoenix-stage"
  labels:
    namespace: phoenix-stage
    helm.sh/chart: edgesql-0.1.0
    app.kubernetes.io/name: edgesql
    app.kubernetes.io/instance: stage
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: sql
  selector:
    app.kubernetes.io/name: edgesql
    app.kubernetes.io/instance: stage
---
# Source: edgesql/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-edgesql
  namespace: "phoenix-stage"
  labels:
    namespace: phoenix-stage
    helm.sh/chart: edgesql-0.1.0
    app.kubernetes.io/name: edgesql
    app.kubernetes.io/instance: stage
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: edgesql
      app.kubernetes.io/instance: stage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edgesql
        app.kubernetes.io/instance: stage
    spec:
      imagePullSecrets:
      - name: ase-ecr-credentials
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: sqldata
          persistentVolumeClaim:
            claimName: edgesql-pvc
      containers:
        - name: edgesql
          image: "ecr.ase-usgva-p21.missionready.local:31001/mcr.microsoft.com/azure-sql-edge:1.0.5"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
              cpu: 125m
            limits:
              memory: 10Gi
              cpu: 1000m
          ports:
            - name: http
              containerPort: 1433
              protocol: TCP
          env:
            - name: MSSQL_PID
              value: Developer
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edgesql-secret
                  key: SA_PASSWORD
            - name: MSSQL_AGENT_ENABLED
              value: "TRUE"
            - name: MSSQL_COLLATION
              value: SQL_Latin1_General_CP1_CI_AS
            - name: MSSQL_LCID
              value: "1033"
          volumeMounts:
            - name: sqldata
              mountPath: /var/opt/mssql
