---
# Source: sqldb/templates/pvc-edge-sql.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edge-sql-pvc
spec:
  storageClassName: ase-node-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# Source: sqldb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "RELEASE-NAME-sqldb-service"
  labels:
    namespace: phoenix-stage
    helm.sh/chart: sqldb-0.1.0
    app.kubernetes.io/name: sqldb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: sql
  selector:
    app.kubernetes.io/name: sqldb
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: sqldb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-sqldb
  labels:
    namespace: phoenix-stage
    helm.sh/chart: sqldb-0.1.0
    app.kubernetes.io/name: sqldb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app.kubernetes.io/name: sqldb
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sqldb
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      imagePullSecrets:
      - name: ase-ecr-credentials
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: sqldata
          persistentVolumeClaim:
            claimName: edge-sql-pvc
      containers:
        - name: sqldb
          securityContext:
            null
          image: "ecr.ase-usgva-p21.missionready.local:31001/mcr.microsoft.com/azure-sql-edge:1.0.5"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
              cpu: 125m
            limits:
              memory: 10Gi
              cpu: 1000m
          ports:
            - name: http
              containerPort: 1433
              protocol: TCP
          env:
            - name: MSSQL_PID
              value: Developer
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vmuTaXjX5QMQTT==
                  key: SA_PASSWORD
            - name: MSSQL_AGENT_ENABLED
              value: "TRUE"
            - name: MSSQL_COLLATION
              value: SQL_Latin1_General_CP1_CI_AS
            - name: MSSQL_LCID
              value: "1033"
          volumeMounts:
            - name: sqldata
              mountPath: /var/opt/mssql
          resources:
            null
