---
# Source: mssql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mssql
  labels:
    helm.sh/chart: mssql-0.1.0
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: mssql
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: mssql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    helm.sh/chart: mssql-0.1.0
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: mssql
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: mssql
---
# Source: mssql/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    helm.sh/chart: mssql-0.1.0
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: mssql
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mssql
      app.kubernetes.io/instance: mssql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mssql
        app.kubernetes.io/instance: mssql
    spec:
      serviceAccountName: mssql
      securityContext:
        {}
      containers:
        - name: mssql
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: mssql/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "mssql-test-connection"
  labels:
    helm.sh/chart: mssql-0.1.0
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: mssql
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['mssql:80']
  restartPolicy: Never
