apiVersion: v1
kind: Service
metadata:
  name: "{{ include "sqldb.fullname" . }}-service"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "sqldb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sqldb.service.type }}
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: sql
  selector:
    {{- include "sqldb.selectorLabels" . | nindent 4 }}
